name: Deploy firmware

on:
  push:
    tags: '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: planck/rev6
            name: planck_rev6
          - board: jj40
            name: jj40
    steps:
    - uses: actions/checkout@v1

    - name: init submodules
      run: make git-submodule

    - name: install dependencies
      run: sudo util/qmk_install.sh

    - name: make ${{ matrix.name }}
      run: make ${{ matrix.board }}:henning

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.name }}_henning.bin
        asset_name: ${{ matrix.name }}_henning_${{ steps.get_version.outputs.VERSION }}.bin
        tag: ${{ github.ref }}
